# Generated by Django 4.0.6 on 2022-10-25 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_link_alter_event_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 25, 12, 11, 44, 202975, tzinfo=utc)),
        ),
    ]
